# Generated by Django 4.1.8 on 2026-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classurvey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplevel',
            name='top_level_name',
            field=models.CharField(max_length=255),
        ),
    ]
