# Generated by Django 4.1.8 on 2026-05-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classurvey', '0002_alter_toplevel_top_level_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopLevelEdgeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('top_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_cases', to='classurvey.toplevel')),
            ],
        ),
    ]
