# Generated by Django 4.1.8 on 2026-06-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classurvey', '0003_topleveledgecase'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='soundanswer',
            index=models.Index(fields=['user_id'], name='soundanswer_user_idx'),
        ),
        migrations.AddIndex(
            model_name='soundanswer',
            index=models.Index(fields=['test_sound', 'user_id'], name='soundanswer_sound_user_idx'),
        ),
        migrations.AddIndex(
            model_name='soundanswer',
            index=models.Index(fields=['test_sound', 'date_created'], name='soundanswer_sound_date_idx'),
        ),
        migrations.AddIndex(
            model_name='testsound',
            index=models.Index(fields=['sound_group'], name='testsound_group_idx'),
        ),
        migrations.AddIndex(
            model_name='userdetailsmodel',
            index=models.Index(fields=['user_id'], name='userdetails_user_idx'),
        ),
    ]
